FROM alpine:3.13

LABEL Guillaume Dupont <gdupont@student.42.fr>

EXPOSE 3306

##ENVIRONNEMENT UPDATE & UPGRADE##
RUN apk update

##OPENRC INSTALL##
RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

##MYSQL INSTALL##
RUN apk add mysql mysql-client
COPY mariadb-server.cnf /etc/my.cnf.d/mariadb-server.cnf
COPY db_init.sh /db_init.sh

##WORDPRESS DATABASE DUMPING##
COPY setup_wordpress.sql /setup_wordpress.sql

#INSTALL TELEGRAF
RUN apk add telegraf
COPY telegraf.conf /etc/telegraf.conf

ENTRYPOINT sh /db_init.sh