FROM alpine:3.13

LABEL Guillaume Dupont <gdupont@student.42.fr>

EXPOSE 3306

##ENVIRONNEMENT UPDATE & UPGRADE##
RUN apk update

RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

##MYSQL INSTALL##
RUN apk add mysql mysql-client

COPY db_init.sh /db_init.sh

ENTRYPOINT sh /db_init.sh