FROM alpine:3.13

EXPOSE 3000

RUN apk update
RUN apk add grafana

RUN apk add openrc

RUN rc-status
RUN touch /run/openrc/softlevel

##Grafana needs a system logger
RUN apk add syslog-ng

RUN sed -i '/^cfg:server.http_addr/d' etc/conf.d/grafana

RUN rm /etc/grafana.ini
COPY grafana.ini /etc/grafana.ini

COPY datasources.yaml /var/lib/grafana/provisioning/datasources/

COPY dashboards.yaml /var/lib/grafana/provisioning/dashboards/
COPY ./dashboards /var/lib/grafana/dashboards/
RUN mkdir /var/log/grafana && touch /var/log/grafana/grafana.log

#INSTALL TELEGRAF
RUN apk add telegraf telegraf-openrc
COPY telegraf.conf /etc/telegraf.conf
RUN sed -i 's/hostname = ""/hostname = "grafana"/g' /etc/telegraf.conf


ENTRYPOINT /sbin/service grafana start && /sbin/service telegraf start && tail -f /dev/null