FROM alpine:3.13

LABEL Guillaume Dupont <gdupont@student.42.fr>

##ENVIRONNEMENT UPDATE & UPGRADE##
RUN apk update

##NGINX SETUP##
RUN apk add nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

#Nginx need this directory to work properly
RUN mkdir /run/nginx/

#A SIMPLE HTML FILE
COPY index.html /var/www/localhost/htdocs/index.html

#SET UP SSL CERTIFICATES FILES
RUN apk add openssl && openssl req -x509 -nodes -days 365 -subj \
"/C=FR/ST=NA/O=NA/CN=ft_services.com" -addext "subjectAltName=DNS:ft_services.com" \
-newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt

RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

#INSTALL TELEGRAF
RUN apk add telegraf telegraf-openrc
COPY telegraf.conf /etc/telegraf.conf
RUN sed -i 's/hostname = ""/hostname = "nginx"/g' /etc/telegraf.conf

EXPOSE 80 443

ENTRYPOINT ["/bin/sh", "-c", "rc-service nginx restart && rc-service telegraf start && tail -f /dev/null"]