FROM alpine:3.13

MAINTAINER Guillaume Dupont <gdupont@student.42.fr>

##ENVIRONNEMENT UPDATE & UPGRADE##
RUN apk update


##NGINX SETUP##
RUN apk add nginx


COPY nginx.conf /etc/nginx/conf.d/nginx.conf

EXPOSE 80 443

ENTRYPOINT nginx -g 'daemon off;' 