FROM alpine:3.13

LABEL Guillaume Dupont <gdupont@student.42.fr>

##PACKAGE UPDATE##
RUN apk update

##NGINX SETUP##
RUN mkdir -p /run/nginx/
RUN apk add nginx && rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf



##PHP INSTALL##
RUN apk add php7-common php7-iconv php7-json php7-gd php7-curl \
php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql \ 
php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext \
php7-ldap php7-ctype php7-dom php7-fpm php7-mbstring php7-session \
php7-openssl php7-pdo_odbc php7-zip php7-sqlite3 php7-apcu \
php7-pdo_pgsql php7-bcmath php7-gd php7-odbc \
php7-pdo_sqlite php7-xmlreader php7-bz2 php7-pdo_dblib php7-gmp


##Phpmyadmin set up##
RUN wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar zxvf phpMyAdmin-5.0.2-all-languages.tar.gz && rm phpMyAdmin-5.0.2-all-languages.tar.gz
RUN mv phpMyAdmin-5.0.2-all-languages /var/www/localhost/htdocs/phpmyadmin
RUN chmod -R 755 /var/www/localhost/htdocs/phpmyadmin
RUN mkdir /var/www/localhost/htdocs/phpmyadmin/tmp/
COPY config.inc.php /var/www/localhost/htdocs/phpmyadmin/config.inc.php


##SET UP SSL CERTIFICATES FILES##
RUN apk add openssl && openssl req -x509 -nodes -days 365 -subj \
"/C=FR/ST=NA/O=NA/CN=ft_services.com" -addext "subjectAltName=DNS:ft_services.com" \
-newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt

RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

#INSTALL TELEGRAF
RUN apk add telegraf telegraf-openrc
COPY telegraf.conf /etc/telegraf.conf
RUN sed -i 's/hostname = ""/hostname = "telegraf"/g' /etc/telegraf.conf


EXPOSE 5000

ENTRYPOINT rc-service nginx start && rc-service php-fpm7 start && rc-service telegraf start && tail -f /dev/null