FROM alpine:3.13
#https://wiki.alpinelinux.org/wiki/WordPress
#https://wiki.alpinelinux.org/wiki/MariaDB
MAINTAINER Guillaume Dupont <gdupont@student.42.fr>

##PACKAGE UPDATE##
RUN apk update

##NGINX SETUP##
RUN apk add nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/nginx.conf

#Nginx need this directory to work properly
RUN mkdir /run/nginx/

##PHP INSTALL##
RUN apk add php7-common php7-iconv php7-json php7-gd php7-curl \
php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql \ 
php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext \
php7-ldap php7-ctype php7-dom

##INSTALL WORDPRESS##
RUN mkdir -p /usr/share/webapps/ ; cd /usr/share/webapps/ 
RUN wget https://wordpress.org/wordpress-5.5.tar.gz
RUN tar -xzvf wordpress-5.5.tar.gz ; rm wordpress-5.5.tar.gz
RUN ln -s /usr/share/webapps/wordpress/ /var/www/localhost/htdocs/wordpress
RUN chown -R nginx /usr/share/webapps/

## INSTALL MARIADB##

RUN apk add mariadb-client mariadb mariadb-doc
RUN mkdir /var/mysql ; mkdir /var/mysql/datadir ; chown -R mysql:mysql /var/mysql
COPY srcs/wordpress/my.cnf /etc/my.cnf

#SET UP SSL CERTIFICATES FILES
RUN apk add openssl && openssl req -x509 -nodes -days 365 -subj \
"/C=FR/ST=NA/O=NA/CN=ft_services.com" -addext "subjectAltName=DNS:ft_services.com" \
-newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt

EXPOSE 5050

ENTRYPOINT /bin/sh