FROM alpine:3.13
MAINTAINER Guillaume Dupont <gdupont@student.42.fr>

##PACKAGE UPDATE##
RUN apk update

##NGINX SETUP##
RUN mkdir -p /run/nginx/
RUN apk add nginx && rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/nginx.conf
# RUN rm /etc/nginx/conf.d/default.conf

##PHP INSTALL##
RUN apk add php7-common php7-iconv php7-json php7-gd php7-curl \
php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql \ 
php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext \
php7-ldap php7-ctype php7-dom php7-fpm php7-mbstring php7-session \
php7-openssl php7-pdo_odbc php7-zip php7-sqlite3 php7-apcu \
php7-pdo_pgsql php7-bcmath php7-gd php7-odbc \
php7-pdo_sqlite php7-xmlreader php7-bz2 php7-pdo_dblib php7-gmp

##INSTALL WORDPRESS##
RUN cd /var/www/localhost/htdocs/ && wget https://wordpress.org/wordpress-5.5.tar.gz && tar -xzvf wordpress-5.5.tar.gz && rm wordpress-5.5.tar.gz
RUN chown -R nginx:nginx /var/www/localhost/htdocs/wordpress
COPY wp-config.php /var/www/localhost/htdocs/wordpress/wp-config.php

##SET UP SSL CERTIFICATES FILES##
RUN apk add openssl && openssl req -x509 -nodes -days 365 -subj \
"/C=FR/ST=NA/O=NA/CN=ft_services.com" -addext "subjectAltName=DNS:ft_services.com" \
-newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key \
-out /etc/ssl/certs/nginx-selfsigned.crt

RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

#INSTALL TELEGRAF
RUN apk add telegraf telegraf-openrc
COPY telegraf.conf /etc/telegraf.conf
RUN sed -i 's/hostname = ""/hostname = "wordpress"/g' /etc/telegraf.conf

EXPOSE 5050

ENTRYPOINT rc-service php-fpm7 start && rc-service nginx start && rc-service telegraf start && tail -f /dev/null