FROM alpine:3.13

LABEL Guillaume Dupont <gdupont@student.42.fr>

##ENVIRONNEMENT UPDATE & UPGRADE##
RUN apk update

#INSTALL OPENRC
RUN apk add openrc
RUN rc-status
RUN touch /run/openrc/softlevel

#INSTALL VSFTPF
RUN apk add vsftpd
RUN rc-update add vsftpd default
COPY vsftpd.conf ./etc/vsftpd/vsftpd.conf

#SET UP SSL CERTIFICATES
RUN apk add openssl && openssl req -x509 -nodes -days 365 -subj \
"/C=FR/ST=NA/O=NA/CN=172.17.0.2" -addext "subjectAltName=DNS:ftps" \
-newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.key \
-out /etc/ssl/private/vsftpd.crt

#FOR MORE SECURITY 
RUN chown root:root /etc/ssl/private/vsftpd*
RUN chmod 600 /etc/ssl/private/vsftpd*

#WE CREATE A LOCAL USER
RUN echo -e "mdp\nmdp\n" | adduser gdupont

#OUR TEST FILE
RUN echo "Le server ftp fonctionne" > /home/gdupont/test.txt

#INSTALL TELEGRAF
RUN apk add telegraf telegraf-openrc
COPY telegraf.conf /etc/telegraf.conf
RUN sed -i 's/hostname = ""/hostname = "ftps"/g' /etc/telegraf.conf

EXPOSE 20 21 40000
ENTRYPOINT  /sbin/service vsftpd restart &&  /sbin/service telegraf start && tail -f /dev/null

