apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - rc-service nginx status
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 40000

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ftp
      port: 21
    - protocol: TCP
      name: data
      port: 20
    - protocol: TCP
      name: data-40000
      port: 40000
      